project_id = "cdubskcrxkqtzpnismle"

[functions.lazada-api]
verify_jwt = false

[functions.update-category-products]
verify_jwt = false

[functions.sync-feed-products]
verify_jwt = false

[functions.track-click]
verify_jwt = false

[functions.resolve-short-links]
verify_jwt = false

[functions.smart-search]
verify_jwt = false

[functions.expand-lazada-db]
verify_jwt = false

[functions.generate-deal-message]
verify_jwt = false

[functions.dino-chat]
verify_jwt = false

[functions.sync-campaigns-manual]
verify_jwt = false

[functions.aliexpress-api]
verify_jwt = false

[functions.decode-external-link]
verify_jwt = false

[functions.telegram-bot-handler]
verify_jwt = false
